### ISSUE TITLE
Server Rendering

### ISSUE THREAD

**Issue by wooyukit** [makotot/react-scrollspy#10]
The component is very nice but could it support server rendering?

**Comment by neemzy** [comment]
Scroll position is irrelevant server-side, so I'd go with no. It would probably render perfectly well, but its behavior has no meaning in such a context.

**Comment by makotot** [comment]
@wooyukit Thanks for the issue :)
Reasons as @neemzy has commented above, There is no plan to support server side rendering at present.

**Comment by feychenie** [comment]
@neemzy, @makotot,  the point of server-side rendering is being able to pre-render the **markup** on the server, and off course not to mimmic on the server-side the **behaviour** your component has. 
It is **_absolutely relevant_** to make this library compatible with server-side rendering, as it is a no-go for many many many projects.

What it means is that your component should be able to do it's first _markup_ render without relying on any DOM methods or variables. Your components _behaviour_ will then be plugged on the markup in the browser.

Ok this is the third time I comment about this subject in your issues, let me just do a PR ;)
