### ISSUE TITLE
offset does not work

### ISSUE THREAD

**Issue by skate473** [makotot/react-scrollspy#111]
i added props `offset={100}` not change anything..

**Comment by watch2raff** [comment]
Hi, i am used negative value and offset work very well offset={-100}.

**Comment by kat-humu** [comment]
Offset isn't working for me either... no changes regardless of positive/negative numbers.

**Comment by phazel** [comment]
It works, you just need to use a large number to notice the difference. I ended up settling on {-800} for my desired result.

**Comment by skate473** [comment]
> It works, you just need to use a large number to notice the difference. I ended up settling on {-800} for my desired result.

Thanks, that's work!
