### ISSUE TITLE
Component not found

### ISSUE THREAD

**Issue by steeply** [makotot/react-scrollspy#123]
Version 3.4.1

Cannot find file: 'Scrollspy.js' does not match the corresponding name on disk: './node_modules/react-scrollspy/lib/scrollspy.js'

**Comment by ricostone** [comment]
Same here, back to 3.3.10 works

**Comment by sbrack8t** [comment]
Same issue here as well.

**Comment by makotot** [comment]
Sorry, fixed in v3.4.2.
Please reopen this issue if it is still not solved.
