### ISSUE TITLE
A few recommendations

### ISSUE THREAD

**Issue by jmeas** [makotot/react-scrollspy#13]
Cool library! I have a few recommendations that might make it less opinionated and a wee bit more customizable:

- I suggest removing the wrapping `nav` element. It's not possible to opt out of it, and it's not really adding anything, right? Consumers can easily add that in on their own if they need to. I have a preference specify the nav markup outside of this lib.
- Adopting a similar API as `ReactTransitionGroup` could be useful. It renders as a `span` unless the person specifies a `component` prop. This way, folks can use `li`, `ul`, `div`, or whatever they want.
- accept a `className` prop to add a custom class name to the list component

I can make a PR if you think any of these are good ideas!

**Comment by makotot** [comment]
Thanks for wonderful recommendations!
> I can make a PR if you think any of these are good ideas!

I agree with all of your recommendations and PR is always welcome :)

**Comment by feychenie** [comment]
I would add some more recommendations :

- remove the `const win = window; const doc = document;` as it breaks server-side rendering. Use the plain `document` and `window` variables in the code instead. This very simple fix made it work for me.

- in your `render()` method, consider that some children can be `null` or an empty string when using conditional display of a menu entry, like :
`{ user.isAdmin && <li><a href="#displayOnlyForAdmin"></a></li> }` which would render either the link or `null` depending on the user.

`const items = React.Children.map(this.props.children, (child, idx) => {
      if (!child) return child;

`

**Comment by makotot** [comment]
I think all of the recommendations in this issue have been supported now.
Thanks for great recommendations :)
