### ISSUE TITLE
Support server-side rendering

### ISSUE THREAD

**Issue by jmeas** [makotot/react-scrollspy#14]
The caching of `window` and `document` at the root level of this lib makes it so that it can't be rendered on the server. Just using the regular ol window and document should fix the problem.

**Comment by makotot** [comment]
Ref : #10 

Sorry, I cannot imagine what is causing the problem on the server-side rendering by this component.
Please show me a example code that cause the problem by caching `window` & `document`.

**Comment by feychenie** [comment]
var win = window;
          ^
ReferenceError: window is not defined

**Comment by feychenie** [comment]
`window` and `document` are not available server-side. 
By calling them right at the beginning of your code, you break everything on the server-side.

But as on the server-side the life-cycle of a component stops after the very first `render()`, these variables can be called in `componentDidMount`, `componentWillUnmount` and `componentWillReceiveProps`, as these methods will never be called on the server.

Right now it is what you are doing in your code, so just removing the caching (which is useless, by the way) and using the plain `window` and `document` variables in the method makes everything work just fine

**Comment by makotot** [comment]
@feychenie @jmeas @wooyukit
Sorry, I had misunderstood about the issue about SSR with this component.
Thanks to @feychenie , just now I published v2.0.0 that supports SSR ;)
