### ISSUE TITLE
how can i set a offsetTop  of this component ?

### ISSUE THREAD

**Issue by 92hackers** [makotot/react-scrollspy#17]
because i have a fixed header on the page when i scroll down the page, so i want to set a offsetTop on this component to jump to the anchor point more precise, is there any ways to achieve ?

**Comment by makotot** [comment]
I think the anchor point's element needs to have `padding-top` that is relative from fixed header.
This component just jumps to the target html internal link, so cannot set offsetTop.

**Comment by 92hackers** [comment]
oh ,thanks.
