### ISSUE TITLE
Failed prop type issue

### ISSUE THREAD

**Issue by gandreadis** [makotot/react-scrollspy#183]
I'm trying to pass a custom component to the `Scrollspy` as enclosing component. I pass to it the component name (like so: `componentTag={MyComponent}`). It renders properly, but when I look in the console, I see this error message:

```
Warning: Failed prop type: Invalid prop `componentTag` supplied to `Scrollspy`.
```

I've also tried passing an instantiated component (`<MyComponent/>`), but that fails entirely, even before rendering.

I have looked in this codebase, and I see that the type of this is either a `string` or `element` ([see here](https://github.com/makotot/react-scrollspy/blob/master/src/js/lib/scrollspy.js#L24)). Should this maybe be an `elementType`, instead? And if not, do you have any suggestions for how I can fix the issue in my own codebase?

**Comment by urish** [comment]
Facing the same issue, and seems like @gandreadis's workaround did the trick. I'm using [patch-package](https://www.npmjs.com/package/patch-package) to automatically apply the patch after every `npm install`:

https://github.com/wokwi/good-arduino-code/commit/ca623893487caa791cf47a68a714bb82728fd739#diff-b9e7517c5528b338b849379647e48a9f

**Comment by urish** [comment]
Related PR: #165

**Comment by gandreadis** [comment]
Thanks for the update! That fixes it :)
