### ISSUE TITLE
_isInView is true so long as any of the item is on the page - leads to surprising behaviour

### ISSUE THREAD

**Issue by cfogelberg** [makotot/react-scrollspy#31]
My webapp is made up of consecutive sections:
    `<section id="1">...</section>`
    `<section id="2">...</section>`
    `<section id="3">...</section>`

From it's definition _isInView (see [line 83](https://github.com/makotot/react-scrollspy/blob/master/src/js/lib/Scrollspy.jsx#L83)) returns true for an element so long as the element's top is above the bottom of the window and its top is below the top.

Because of how getElemsViewState goes through the components one by one until it finds one in view (e.g. see [line 50](https://github.com/makotot/react-scrollspy/blob/master/src/js/lib/Scrollspy.jsx#L50)), so long as a component is on the screen at all then the next component will not be highlighted. (Alternately, if scrolling in the opposite order to the way the item keys are defined, the next component will be highlighted as soon as any of it is on screen).

This behaviour is especially strange in my webapp: When clicking on a link to a section, the previous section's navbar item is highlighted. It is made worse because I have a 75px fixed-top navbar as well.

As solutions to this I suggest finding the scrollspy item that occupies the middle of the page and specifying that this element is in view instead. E.g. changing:

```
`return (elTop < scrollBottom) && (elBottom > scrollTop)`
```

To:

```
`var midpoint = scrollBottom + (scrollTop - scrollBottom) / 2;
 return (elTop < midpoint) && (elBottom > midpoint);`
```

I've made this change locally and prefer it. I'd be happy to submit a pull request as well, but because it is a behavioural change it is better to open this issue first for discussion. E.g. it might be better to make this new behaviour optional via a property.

**Comment by makotot** [comment]
Same as #17, isn't it ?
  
  
> This behaviour is especially strange in my webapp: When clicking on a link to a section, the previous section's navbar item is highlighted. It is made worse because I have a 75px fixed-top navbar as well.

I don't want to change original behavior of this component that the first element in view to be active. 
It does not solve this issue to add `padding-top` to the sections ?
If we add a option to solve it, it might be an adjusted value users can specify. I think that it is better if you can be processed at the position desired with any of the adjustment value.

**Comment by cfogelberg** [comment]
Adding padding does solve the issue but it isn't the graphical appearance that works best in this situation. Using an offset value could do it, if I have an opportunity I'll look at putting together a PR with that in it.

**Comment by makotot** [comment]
Sorry for very late reply. Added `offset` option in v2.5.0.

**Comment by makotot** [comment]
I think v2.5.0 make this issue solved, so i close it,  but feel free to reopen this issue.
