### ISSUE TITLE
Can you add a offset

### ISSUE THREAD

**Issue by daialihexiaoniu** [makotot/react-scrollspy#33]
I have a request offset.
I'd like a offset which as bootstrap.
I try to add a value in the method ' _isInView', which can be used.
![Uploading Screenshot from 2016-10-13 16:31:04.png…]()

**Comment by rickyrauch** [comment]
+1

**Comment by juliat** [comment]
+1

**Comment by makotot** [comment]
I'm sorry for very late reply. Added `offset` option in v2.5.0.
