### ISSUE TITLE
Scrollspy can not be used in a scrollable container

### ISSUE THREAD

**Issue by adamduren** [makotot/react-scrollspy#48]
Currently scrollspy watches for scroll events on the documentElement. This makes it so that ScrollSpy can not be used in a scrollable container. Attached is a sample use case to demonstrate the need for this feature.

![image](https://cloud.githubusercontent.com/assets/581097/22482697/230890c4-e7c8-11e6-9de8-39b0d7b88597.png)

#47 is currently out for review in attempt to support this use case. Looking forward to your thoughts!

**Comment by makotot** [comment]
`rootEl` props added in v3.1.0 :)
