### ISSUE TITLE
React version

### ISSUE THREAD

**Issue by neemzy** [makotot/react-scrollspy#5]
Hi,

I tried to use this lib on a project powered by React v0.14.6 and it didn't work, as my version seemed to conflict with the one that is used internally (given your version constraint is `^0.13.3`).

I'd suggest:
- raising your version constraint; I can confirm your lib works up to v0.14.6 as I said
- setting React as a `peerDependency` to avoid having it installed in your lib's own `node_modules` folder, and use the project's instead - having multiple versions of React coexisting is never a good idea in my experience.

Thanks for the lib anyway, it works great now :)

Cheers,

**Comment by makotot** [comment]
Thanks for suggestion :) React has moved to peerDependencies in v0.2.0 which would avoid having multiple versions of react.
