### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ./throttle in <MY_DIR>/node_modules/react-scrollspy

### ISSUE THREAD

**Issue by simonbergstrom** [makotot/react-scrollspy#56]
When npm install this and trying to require i get this error from my webpack-dev-server.

ERROR in ./~/react-scrollspy/scrollspy.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./throttle in XXX/node_modules/react-scrollspy
 @ ./~/react-scrollspy/scrollspy.js 51:16-37

**Comment by makotot** [comment]
Thanks! Now, you can install v3.0.2 is resolved this issue :)
