### ISSUE TITLE
Add feature of not registering scroll event

### ISSUE THREAD

**Issue by ImanMh** [makotot/react-scrollspy#61]
Since scroll events are heavy, that would be grate if you could add the feature of disabling scroll event registration. This way I could have my own scroll event and pass it's pulses to many other components.

**Comment by makotot** [comment]
Added [`.offEvent`](https://github.com/makotot/react-scrollspy#offevent) method in v3.2.0 ;)

**Comment by ImanMh** [comment]
Thank you very much for this awesome project.
