### ISSUE TITLE
The position comes back to it's initial state after a few milliseconds

### ISSUE THREAD

**Issue by ImanMh** [makotot/react-scrollspy#66]
Everything works fine, but when I click on a menu item, My scroll position comes back to it's previous position after a few milliseconds. For example if I'm in section #1 and I click on #2, it takes me to #2 but comes back to #1 after about 100ms. What is your guess about this issue?

**Comment by makotot** [comment]
Sorry for late reply.
Wired. Please give me more detailed information to reproduce same behavior, If this issue remained as unresolved.
