### ISSUE TITLE
Smooth Scroll

### ISSUE THREAD

**Issue by michelarteta** [makotot/react-scrollspy#69]
Hello is smooth scrolling supported via props?

**Comment by makotot** [comment]
There is no plan to implement smooth scroll. 
Why don't you use smooth scroll lib like https://github.com/iamdustan/smoothscroll ?

**Comment by kevincolten** [comment]
Your demo page works if you put `scroll-behavior: smooth;` on the `html` tag

**Comment by corysimmons** [comment]
Nice one @kevincolten 

For anyone using styled-components or Emotion, you can add global styles using those plugins e.g. https://emotion.sh/docs/globals#___gatsby to target the `html` selector from specific pages.
