### ISSUE TITLE
Coloring the anchor tag?

### ISSUE THREAD

**Issue by AlmahaAlmalki** [makotot/react-scrollspy#72]
#Hi,

I tried to change the color of the anchor tags when it's active, but it didn't work since the styling is passed to the `<li>` tag? So is there a way where I can pass the class to the <a> tags? 

Thanks

**Comment by xarg** [comment]
Hey @AlmahaAlmalki if you're still looking. I fixed this by applying the style like so:

```
li a.activeLink {
  color: red;
}
```

**Comment by AlmahaAlmalki** [comment]
Thanks, @xarg :)
