### ISSUE TITLE
Module not found : scrollspy.js 

### ISSUE THREAD

**Issue by gauravprwl14** [makotot/react-scrollspy#73]
hi,

when i install the latest build version which is 3.3.4, i am getting below error 

Module build failed: Error: ENOENT: no such file or directory, open '/Users/sahusoft/Sites/projects/merge_wos_with_jaipur_team/wos-client/node_modules/react-scrollspy/scrollspy.js'

when i checked the lib folder it has Scrollspy.js instead of scrollspy.js.

**Comment by makotot** [comment]
How did you install this lib? Maybe the module you installed is not this lib or not latest version. 
react-scrollspy does not have a file such like `node_modules/react-scrollspy/scrollspy.js`. `ScrollSpy.js` should be in `node_modules/react-scrollspy/lib/`.

**Comment by makotot** [comment]
Cannot reproduced. Feel free to reopen this issue if the same error occured.

**Comment by pryahin** [comment]
Hello,

I got this error today. The case is case sensitivity. I could solve it locally by renaming the "main" field in the file node_modules/react-scrollspy /package.json: "./lib/Scrollspy.js" -> "./lib/scrollspy.js". Each time on all devices manually change this line torment. Can you correct the path in this field?

Version 3.4.0 installs ./lib/Scrollspy.js
Version 3.4.1 installs ./lib/scrollspy.js
![image](https://user-images.githubusercontent.com/17345139/69551916-92369c00-0fae-11ea-86e8-0165ddf6685b.png)
