### ISSUE TITLE
cannot npm install

### ISSUE THREAD

**Issue by nineleaps-aditya** [makotot/react-scrollspy#82]
`ERROR: [Errno 2] No such file or directory: 'run'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-scrollspy@3.3.5 prepublish: `yarn run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-scrollspy@3.3.5 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nineleaps/.npm/_logs/2018-06-07T06_40_02_795Z-debug.log
`
`
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nineleaps/.npm/_logs/2018-06-07T06_41_17_276Z-debug.log

`

**Comment by makotot** [comment]
Cannot reproduce.
